version: '3.8'

services:
  bot-tele:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: namtiamo/tele:v1.0.1
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PYTHONUNBUFFERED=1
    volumes:
      # - .:/app
      - ./data:/app/data
      - ./bot-logs:/app/bot-logs  # Mount folder bot-logs cho log files
      # - ./config.py:/app/config.py
    network_mode: host   # 👉 dùng mạng host, bỏ networks ở dưới
    dns:
      - 8.8.8.8
      - 1.1.1.1

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ❌ Bỏ toàn bộ phần này đi nếu dùng host mode
# networks:
#   bot-network:
#     driver: bridge

volumes:
  bot-data:
    driver: local
  bot-logs:
    driver: local
